version: '3.8'

services:
  ml-container:
    container_name: ml_environment
    build: ./docker
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "8888:8888"  # Exposes Jupyter Notebook
    stdin_open: true
    tty: true
    command: ["jupyter", "notebook", "--ip=0.0.0.0", "--allow-root", "--NotebookApp.token=''"]
